band:
- F606W
- F814W
fitting:
  mcmc_settings:
    burnin_step: 0
    iteration_step: 3000
    walker_ratio: 16
  psf_iteration: false
  psf_iteration_settings:
    block_neighbor: 0.0
    psf_iteration_factor: 0.5
    psf_iteration_num: 50
    psf_symmetry: 4
  pso: true
  pso_settings:
    num_iteration: 150
    num_particle: 192
  sampler: MCMC
  sampling: true
guess_params:
  lens:
    0:
      theta_E: 1.1
kwargs_constraints:
  joint_lens_light_with_lens_light:
  - - 0
    - 1
    - - e1
      - e2
      - center_x
      - center_y
  - - 0
    - 2
    - - e1
      - e2
      - R_sersic
      - center_x
      - center_y
  - - 0
    - 3
    - - e1
      - e2
      - center_x
      - center_y
  - - 1
    - 3
    - - R_sersic
  joint_lens_with_light:
  - - 0
    - 0
    - - center_x
      - center_y
  joint_source_with_source:
  - - 0
    - 1
    - - center_x
      - center_y
  - - 0
    - 2
    - - center_x
      - center_y
  - - 0
    - 3
    - - center_x
      - center_y
  - - 1
    - 3
    - - e1
      - e2
      - R_sersic
lens_light_option:
  fix:
    0:
      n_sersic: 4.0
    1:
      n_sersic: 1.0
    2:
      n_sersic: 4.0
    3:
      n_sersic: 1.0
lens_option:
  centroid_init:
  - 0.0
  - 0.0
  constrain_position_angle_from_lens_light: 15
mask:
  centroid_offset:
  - - 0.0974
    - -0.0138
  - - 0.0913
    - -0.0218
  custom_mask:
  - null
  - null
  dec_at_xy_0:
  - 0.44292536505789704
  - 3.4082179709415605
  extra_regions:
  - - - 0.0974
      - -0.0138
      - 0.4
  - - - 0.0913
      - -0.0218
      - 0.4
  ra_at_xy_0:
  - -4.201151199160345
  - 3.083660472462788
  radius:
  - 2.65
  - 2.65
  size:
  - 120
  - 130
  transform_matrix:
  - - - 0.038685859241796176
      - 0.031333327410876244
    - - 0.03128397642449844
      - -0.03866606584213006
  - - - 0.002496677795267337
      - -0.04993760814084869
    - - -0.04993744934635606
      - -0.002496673283514106
model:
  lens:
  - PEMD
  - SHEAR_GAMMA_PSI
  lens_light:
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  lens_light_band_indices:
  - 0
  - 0
  - 1
  - 1
  point_source: []
  source_light:
  - SHAPELETS
  - SERSIC_ELLIPSE
  - SHAPELETS
  - SERSIC_ELLIPSE
  source_light_band_indices:
  - 0
  - 0
  - 1
  - 1
numeric_option:
  supersampling_factor:
  - 2
pixel_size: 0.04
point_source_option:
  bound: 0.0
  dec_init: []
  ra_init: []
source_light_option:
  n_max:
  - 6
  - 6
  shapelet_scale_logarithmic_prior: true
system_name: SDSSJ0330-0020
