band:
- F475X
- F600LP
- F606W
fitting:
  mcmc_settings:
    burnin_step: 0
    iteration_step: 3000
    walker_ratio: 16
  psf_iteration: false
  psf_iteration_settings:
    block_neighbor: 0.0
    psf_iteration_factor: 0.5
    psf_iteration_num: 50
    psf_symmetry: 4
  pso: true
  pso_settings:
    num_iteration: 150
    num_particle: 192
  sampler: MCMC
  sampling: true
guess_params:
  lens:
    0:
      theta_E: 1.21
kwargs_constraints:
  joint_lens_light_with_lens_light:
  - - 0
    - 1
    - - e1
      - e2
      - center_x
      - center_y
  - - 0
    - 2
    - - e1
      - e2
      - R_sersic
      - center_x
      - center_y
  - - 0
    - 3
    - - e1
      - e2
      - center_x
      - center_y
  - - 1
    - 3
    - - R_sersic
  - - 0
    - 4
    - - e1
      - e2
      - R_sersic
      - center_x
      - center_y
  - - 0
    - 5
    - - e1
      - e2
      - center_x
      - center_y
  - - 1
    - 5
    - - R_sersic
  joint_lens_with_light:
  - - 0
    - 0
    - - center_x
      - center_y
  joint_source_with_source:
  - - 0
    - 1
    - - center_x
      - center_y
  - - 0
    - 2
    - - center_x
      - center_y
  - - 0
    - 3
    - - center_x
      - center_y
  - - 1
    - 3
    - - e1
      - e2
      - R_sersic
  - - 0
    - 4
    - - center_x
      - center_y
  - - 0
    - 5
    - - center_x
      - center_y
  - - 1
    - 5
    - - e1
      - e2
      - R_sersic
lens_light_option:
  fix:
    0:
      n_sersic: 4.0
    1:
      n_sersic: 1.0
    2:
      n_sersic: 4.0
    3:
      n_sersic: 1.0
    4:
      n_sersic: 4.0
    5:
      n_sersic: 1.0
lens_option:
  centroid_init:
  - 0.0
  - 0.0
  constrain_position_angle_from_lens_light: 15
mask:
  centroid_offset:
  - - 0.1651
    - 0.0104
  - - 0.1437
    - 0.0196
  - - -0.1796
    - 0.2059
  custom_mask:
  - null
  - null
  - null
  dec_at_xy_0:
  - 1.1571373281154476
  - 1.157137324164613
  - 2.040904887432786
  extra_regions:
  - - - 0.1651
      - 0.0104
      - 0.25
    - - 0.7
      - -2.0
      - 0.2
  - - - 0.1437
      - 0.0196
      - 0.25
  - - - -0.1796
      - 0.2059
      - 0.25
    - - 0.5
      - -2.0
      - 0.5
  ra_at_xy_0:
  - -3.191779736106123
  - -3.191779425634833
  - 2.887440456709749
  radius:
  - 2.2
  - 2.2
  - 2.2
  size:
  - 120
  - 120
  - 50
  transform_matrix:
  - - - 0.03625580550625872
      - 0.016940523428843335
    - - 0.016949968188228207
      - -0.03623559032348567
  - - - 0.03625579828537414
      - 0.016940525475206414
    - - 0.016949967307632527
      - -0.03623558937704274
  - - - -0.01694276879018482
      - -0.09855484947820514
    - - -0.09857542043204255
      - 0.0169392249347311
model:
  lens:
  - PEMD
  - SHEAR_GAMMA_PSI
  lens_light:
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  lens_light_band_indices:
  - 0
  - 0
  - 1
  - 1
  - 2
  - 2
  point_source: []
  source_light:
  - SHAPELETS
  - SERSIC_ELLIPSE
  - SHAPELETS
  - SERSIC_ELLIPSE
  - SHAPELETS
  - SERSIC_ELLIPSE
  source_light_band_indices:
  - 0
  - 0
  - 1
  - 1
  - 2
  - 2
numeric_option:
  supersampling_factor:
  - 2
pixel_size: 0.04
point_source_option:
  bound: 0.0
  dec_init: []
  ra_init: []
source_light_option:
  n_max:
  - 8
  - 8
  - 8
  shapelet_scale_logarithmic_prior: true
system_name: SL2SJ1358+5459
