band:
- F606W
- F814W
fitting:
  mcmc_settings:
    burnin_step: 0
    iteration_step: 1500
    walker_ratio: 16
  psf_iteration: false
  psf_iteration_settings:
    block_neighbor: 0.0
    psf_iteration_factor: 0.5
    psf_iteration_num: 50
    psf_symmetry: 4
  pso: true
  pso_settings:
    num_iteration: 150
    num_particle: 192
  sampler: MCMC
  sampling: true
guess_params:
  lens:
    0:
      e1: -0.0812488252533865
      e2: 0.04503695925785647
      theta_E: 1.42
kwargs_constraints:
  joint_lens_light_with_lens_light:
  - - 0
    - 1
    - - e1
      - e2
      - center_x
      - center_y
  - - 0
    - 2
    - - e1
      - e2
      - R_sersic
      - center_x
      - center_y
  - - 0
    - 3
    - - e1
      - e2
      - center_x
      - center_y
  - - 1
    - 3
    - - R_sersic
  joint_lens_with_light:
  - - 0
    - 0
    - - center_x
      - center_y
  joint_source_with_source:
  - - 0
    - 1
    - - center_x
      - center_y
  - - 0
    - 2
    - - center_x
      - center_y
  - - 0
    - 3
    - - center_x
      - center_y
  - - 1
    - 3
    - - e1
      - e2
      - R_sersic
lens_light_option:
  fix:
    0:
      n_sersic: 4.0
    1:
      n_sersic: 1.0
    2:
      n_sersic: 4.0
    3:
      n_sersic: 1.0
  prior_lens_light_ellip: 15
lens_option:
  centroid_init:
  - 0.0
  - 0.0
  constrain_position_angle_from_lens_light: 15
mask:
  centroid_offset:
  - - -0.1106
    - -0.2391
  - - -0.0147
    - -0.2693
  custom_mask:
  - null
  - null
  dec_at_xy_0:
  - -1.0140856115525416
  - -0.5801143617633344
  extra_regions:
  - - - -0.1106
      - -0.2391
      - 0.4
  - - - -0.0147
      - -0.2693
      - 0.4
  mask_edge_pixel:
  - 0
  - 5
  ra_at_xy_0:
  - -4.461403973688885
  - 3.6295347903093775
  radius:
  - 2.65
  - 2.65
  size:
  - 130
  - 104
  transform_matrix:
  - - - 0.026487675322669445
      - 0.04214930888792878
    - - 0.04208998840200303
      - -0.0264886713011947
  - - - -0.04045172484705861
      - -0.029347021120429417
    - - -0.029325446915739906
      - 0.04048149233426557
model:
  lens:
  - PEMD
  - SHEAR_GAMMA_PSI
  lens_light:
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  - SERSIC_ELLIPSE
  lens_light_band_indices:
  - 0
  - 0
  - 1
  - 1
  point_source: []
  source_light:
  - SHAPELETS
  - SERSIC_ELLIPSE
  - SHAPELETS
  - SERSIC_ELLIPSE
  source_light_band_indices:
  - 0
  - 0
  - 1
  - 1
numeric_option:
  supersampling_factor:
  - 2
pixel_size: 0.04
point_source_option:
  bound: 0.0
  dec_init: []
  ra_init: []
source_light_option:
  n_max:
  - 10
  - 10
  shapelet_scale_logarithmic_prior: true
system_name: SDSSJ1213+6708
